[package]
name = "reth-ethereum-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Implementation of rpc for layer one ethereum"

[lints]
workspace = true

[dependencies]
# reth
reth-rpc-builder.workspace = true
reth-rpc.workspace = true
reth-tasks.workspace = true
reth-provider.workspace = true
reth-evm.workspace = true
reth-transaction-pool.workspace = true
reth-network-api.workspace = true

